### PR TITLE
overwrite parent to add child

### LINKED ISSUE #8: Overwrite parent node
When a new node with childe_name equal to an existing child that was made as a placeholder for the tree, it is not added to the tree. 
Solution: overwrite the placeholder parent node with the child.

### PR DESCRIPTION
**Pull request by Mahir-Sparkess**
closes #8

### CODE REVIEW

**Comment by rsmith013** [comment]
@Mahir-Sparkess I am not sure this works. I have written some tests in https://github.com/cedadev/ceda-directory-tree/pull/10

**Comment by Mahir-Sparkess** [comment]
I'll have a look, my code only works for the first level of nodes, couldn't test what the behaviour would be deeper in the tree.

**Comment by rsmith013** [comment]
I only tried it with two paths. I stuck a load of print statements in and couldn't work out how it was supposed to work.

**Comment by Mahir-Sparkess** [comment]
I believe this solution is better:
- New update method for directory_node
- Update node if the last visited node is not a dataset

Since the add child traverses the tree and it will get to [L65](https://github.com/cedadev/ceda-directory-tree/blob/f7c930f6e2297dd5e3eaf2dc41f25a074c38755e/directory_tree/dataset_node.py#L65)
https://github.com/cedadev/ceda-directory-tree/blob/f7c930f6e2297dd5e3eaf2dc41f25a074c38755e/directory_tree/dataset_node.py#L61-L68

But the node creation part fails since the node already exists, so I just update said node instead with a new update method and now all the tests pass 🥳

**Comment by rsmith013** [comment]
looks good. Can you change the PR target to be the branch with the test in?

**Comment by Mahir-Sparkess** [comment]
I think that changes the target branch to adding_tests right?

Though it's not showing the change of removing the bit between L63-66

**Pull request merged**
